# Generated by Django 3.2.5 on 2021-08-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posts_created', models.IntegerField(default=0)),
                ('posts_updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('story_url', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
                ('posted_by', models.CharField(max_length=200)),
                ('poster_profile_url', models.URLField()),
                ('hn_post_url', models.URLField()),
                ('crawl_run', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='posts.crawlrun')),
            ],
        ),
    ]
