# Generated by Django 3.2.5 on 2021-08-01 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ManyToManyField(related_name='post_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='read_by',
            field=models.ManyToManyField(related_name='post_read_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
